// <auto-generated />
using System;
using AgriculturalLandManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriculturalLandManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251023185916_AddFeatureToCorner4")]
    partial class AddFeatureToCorner4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AgriculturalLandManagement.Models.Corner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LandId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LandId");

                    b.ToTable("Corners");
                });

            modelBuilder.Entity("AgriculturalLandManagement.Models.CornerImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CornerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("CornerId")
                        .IsUnique();

                    b.ToTable("CornerImages");
                });

            modelBuilder.Entity("AgriculturalLandManagement.Models.Land", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Area")
                        .HasColumnType("REAL");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Production")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lands");
                });

            modelBuilder.Entity("AgriculturalLandManagement.Models.Corner", b =>
                {
                    b.HasOne("AgriculturalLandManagement.Models.Land", "Land")
                        .WithMany("Corners")
                        .HasForeignKey("LandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Land");
                });

            modelBuilder.Entity("AgriculturalLandManagement.Models.CornerImage", b =>
                {
                    b.HasOne("AgriculturalLandManagement.Models.Corner", "Corner")
                        .WithOne("Image")
                        .HasForeignKey("AgriculturalLandManagement.Models.CornerImage", "CornerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corner");
                });

            modelBuilder.Entity("AgriculturalLandManagement.Models.Corner", b =>
                {
                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("AgriculturalLandManagement.Models.Land", b =>
                {
                    b.Navigation("Corners");
                });
#pragma warning restore 612, 618
        }
    }
}
